"""Added username

Revision ID: 524eee9e82cf
Revises: e09553d70297
Create Date: 2023-10-11 14:50:20.431914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '524eee9e82cf'
down_revision = 'e09553d70297'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=20), nullable=False))
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
